# -*- coding: utf-8 -*-
"""CIFAR-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AFLfuZ8GWM8w72wmfQQnIRPvfo0Xtr5l
"""

!pip install tensorflow  keras

import tensorflow as tf
from tensorflow.keras import datasets, layers, models

#  Load CIFAR-10 dataset
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

# Normalize pixel values to [0,1]
train_images, test_images = train_images / 255.0, test_images / 255.0

# CIFAR-10 has 10 classes
class_names = ["airplane", "automobile", "bird", "cat", "deer",
               "dog", "frog", "horse", "ship", "truck"]

# ✅ Build CNN model (same structure works)
model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(32,32,3)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

"""here we got the warning error to add Explicit Input layers , so in other we did"""

# ✅ Build CNN model (same structure works)
model = models.Sequential([
    tf.keras.Input(shape=(32,32,3)),   # ✅ Explicit Input layer
    layers.Conv2D(32, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# ✅ Compile and train
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(train_images, train_labels, epochs=10,
                    validation_data=(test_images, test_labels))

"""we could add early stopping here , to save epochs timing and best results . Currently i used the process as it is for training on CIFAR-10

##Key Observations
- Training accuracy is higher than validation accuracy → classic overfitting.
- Validation accuracy plateaued around 70% → the model has learned useful features but needs regularization or architecture tweaks to go further.
- Without early stopping, the model kept training even after validation loss stopped improving (around epoch 6–7).
"""